### ISSUE TITLE
Please adopt a different naming convention for the "starter" artifact

### ISSUE THREAD

**Issue by dsyer** [paypal/resteasy-spring-boot#2]
It's great to see people developing new Spring Boot features, so thanks for making this available. The Spring Boot team requests that you not use the "spring-boot-starter" prefix for your artifacts though (here's a link to the user guide explaining the policy: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming). Can you change it please?

**Comment by fabiocarvalho777** [comment]
Hello,
Sure, no problem. Sorry, we were not aware of this guideline to name starters. Thanks for letting us know.
So, I just read it, and sounds like I could rename it to **resteasy-spring-boot-starter** (instead of **spring-boot-starter-resteasy**). Please confirm to me if this new name would be Ok.

**Comment by dsyer** [comment]
That works fine for us.

**Comment by fabiocarvalho777** [comment]
Renamed:
https://github.com/paypal/resteasy-spring-boot/commit/ba348425cfac283ee8e0c1693e1395ee92bbba16
https://github.com/paypal/resteasy-spring-boot/commit/b80150f8ffa3866861a2dc0e144342559cce8213
