### ISSUE TITLE
Not possible to use application property in application.yml

### ISSUE THREAD

**Issue by leonardschneider** [paypal/resteasy-spring-boot#35]
Because JAXRS_APP_CLASSES_PROPERTY (resteasy.jaxrs.app) is a parent of JAXRS_APP_CLASSES_DEFINITION_PROPERTY  (resteasy.jaxrs.app.registration) which violates YAML syntax.

**Comment by fabiocarvalho777** [comment]
Hello Leonard. Thank you very much for reporting it. I will take a look at this issue as soon as possible (very likely by the end of this week) and, if necessary, provide a new release with the fix immediately. Thanks again.

**Comment by fabiocarvalho777** [comment]
By the way, meanwhile you can still use the starter  normally by not setting the properties, which will make it use the default configuration, or by using a properties file instead of yaml if possible.

**Comment by fabiocarvalho777** [comment]
Hello. I just want to let you know that I have just confirmed that it is indeed a bug, and I have already fixed it in my dev box. I will just update documentation and then push the fix and release a new version with the fix. All of that should be done in a few days. I will let you know. Thanks again for reporting it.

**Comment by fabiocarvalho777** [comment]
Hey @leonardschneider , this issue has been fixed. Please, instead of `resteasy.jaxrs.app`, use `resteasy.jaxrs.app.classes` to define your JAX-RS classed, as explained [here](https://github.com/paypal/resteasy-spring-boot/blob/develop/mds/USAGE.md#jax-rs-application-registration-methods). You can test that with version `2.2.0-SNAPSHOT`. Please let me know how it goes. I am going to release version `2.2.0-RELEASE` at some point this week, unless you see any problem with this solution.

**Comment by fabiocarvalho777** [comment]
Version 2.2.0 (with this fix) has been released.

**Comment by leonardschneider** [comment]
Hi,

Sorry, just catching up now. Thanks a lot for the fix. I will give it a try.
