### ISSUE TITLE
Questions about parent POM

### ISSUE THREAD

**Issue by zachariahyoung** [paypal/resteasy-spring-boot#38]
I just watched your Spring One session on how you have configured Spring Boot.  I would like to ask one question.  On each of your spring boot applications is the parent pom still spring boot.  Or do you have a parent pom for Paypal?

I appears that you just have a core starter pom then sub starter poms for each type of applications.

Thanks

Zach

**Comment by fabiocarvalho777** [comment]
Hello Zach,

In our PayPal Spring Boot applications the parent pom is not the Spring Boot one, it is a PayPal one actually.

What we do is we bring Spring Boot BOM as a managed dependency, pom type and import scope, and that works pretty well. As seen below.

````
<dependencyManagement>

    ...

    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>

    ...

<dependencyManagement>
```

**Comment by zachariahyoung** [comment]
One last question, do your starter POM referrence the Paypal Parent POM?

**Comment by fabiocarvalho777** [comment]
I am not sure I understood your question but, just to clarify, this RESTEasy Spring Boot starter is 100% free of any PayPal or any proprietary code.

Now, talking about the PayPal starters we have, yes, they somehow reference the PayPal parent POM, but not was you might think, since what I am calling here "PayPal parent POM" is more complex than a single POM file, it has many different layers. So, they layer an application would extend from (the deepest one) is not the same as the one extended from a PayPal starter. 

Also, going back to my first answer, you also have to keep in mind that when you chose to use Spring Boot BOM as a managed dependency (instead of having Spring Boot as a parent) you lose other stuff, like Maven plugins configurations for example. That you would have to do by yourself.

Hope that answers your question.
